package com.liiga.hockeysite.model.penalty.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum PenaltyName {
    PENALTY_NAME_TRIPPING("TRIPPING"),
    PENALTY_NAME_HOLDING("HOLDING"),
    PENALTY_NAME_BOARDING("BOARDING"),
    PENALTY_NAME_ROUGHING("ROUGHING"),
    PENALTY_NAME_ELBOWING("ELBOWING"),
    PENALTY_NAME_HOOKING("HOOKING"),
    PENALTY_NAME_SLASHING("SLASHING"),
    PENALTY_NAME_DELAY_OF_THE_GAME("DELAY_OF_THE_GAME"),
    PENALTY_NAME_KNEEING("KNEEING"),
    PENALTY_NAME_FIGHTING("FIGHTING"),
    PENALTY_NAME_GOALIE_INTERFERENCE("GOALIE_INTERFERENCE"),
    PENALTY_NAME_HIGH_STICKING("HIGH_STICKING");
    private final String name;
}
