package com.liiga.hockeysite.model.player.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum PlayerNationality {
    PLAYER_NATIONALITY_CAN("CANADA"),
    PLAYER_NATIONALITY_USA("USA"),
    PLAYER_NATIONALITY_SWE("SWEDEN"),
    PLAYER_NATIONALITY_FIN("FINLAND"),
    PLAYER_NATIONALITY_GER("GERMANY"),
    PLAYER_NATIONALITY_SWI("SWITZERLAND"),
    PLAYER_NATIONALITY_DEN("DENMARK"),
    PLAYER_NATIONALITY_FRA("FRANCE"),
    PLAYER_NATIONALITY_SVK("SLOVAKIA"),
    PLAYER_NATIONALITY_SLV("SLOVENIA"),
    PLAYER_NATIONALITY_RUS("RUSSIA"),
    PLAYER_NATIONALITY_BLR("BELARUS"),
    PLAYER_NATIONALITY_KAZ("KAZAKHSTAN"),
    PLAYER_NATIONALITY_LAT("LATVIA"),
    PLAYER_NATIONALITY_EST("ESTONIA"),
    PLAYER_NATIONALITY_POL("POLAND"),
    PLAYER_NATIONALITY_CZE("CZECHIA"),
    PLAYER_NATIONALITY_ITA("ITALY"),
    PLAYER_NATIONALITY_LIT("LITHUANIA"),
    PLAYER_NATIONALITY_NOR("NORWAY"),
    PLAYER_NATIONALITY_HUN("HUNGARY"),
    PLAYER_NATIONALITY_ENG("ENGLAND");
    private final String name;
}
